# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterField(
            model_name='question',
            name='quest_text',
            field=models.CharField(max_length=200, verbose_name='test'),
        ),
    ]
